/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.*;

import javax.xml.bind.JAXBException;

import java.io.IOException;

public class App {

	public static void main(String[] args) {
		Zombie fred=new Zombie("Fred",40);
		
		fred.eat("Jack");
		fred.eat("Sshit");
		fred.eat("Joe Biden");
		fred.eat("George Washington");
		fred.eat("Michelle Obama");
		try{
			fred.marshalTo("./fred.xml");
		}catch(JAXBException|IOException e){
			e.printStackTrace();
		}
	}
}
